/**
 * The maps that are already there on a fresh install.
 *
 * Both are original terrain — eleven parameters and a seed, generated by the
 * same forge the user gets. Nothing here is traced from anyone else's world;
 * if you want a real place, the import button reads a greyscale heightmap and
 * that is the honest way to get one in.
 *
 * The marker coordinates are baked rather than sited at runtime. Running the
 * generator twice would give the same answer, but it would also mean paying
 * for two full terrain builds during boot to place eighteen dots — and boot is
 * exactly where that cost is least welcome. Regenerate with the script under
 * tools/ if the noise ever changes underneath them.
 */
import type { MapDoc } from "./types";

export const EXAMPLE_DOCS: MapDoc[] = [
  {
    format: "voidshell.map",
    version: 1,
    name: "Kaldmark",
    note: "a northern province of holds, fells and frozen coast",
    params: {
      seed: 20489,
      size: 192,
      extentKm: 260,
      reliefM: 4200,
      seaLevel: 0.4,
      ridges: 0.72,
      continentality: 0.62,
      warp: 0.52,
      erosion: 18,
      latitude: 0.82,
      aridity: 0.24,
    },
    markers: [
      { id: "m0", name: "Hrimspire", u: 0.5183, v: 0.534, kind: "peak" },
      { id: "m1", name: "Vardholm", u: 0.6545, v: 0.4869, kind: "hold" },
      { id: "m2", name: "Kelvik", u: 0.8534, v: 0.1099, kind: "port" },
      { id: "m3", name: "Aussgard", u: 0.2984, v: 0.7749, kind: "town" },
      { id: "m4", name: "Grennbarrow", u: 0.2775, v: 0.1361, kind: "hold" },
      { id: "m5", name: "Thornmere", u: 0.3455, v: 0.555, kind: "ruin" },
      { id: "m6", name: "Skaldwatch", u: 0.4293, v: 0.3979, kind: "town" },
      { id: "m7", name: "Nirhaven", u: 0.2408, v: 0.3089, kind: "camp" },
      { id: "m8", name: "Belstead", u: 0.1257, v: 0.8272, kind: "port" },
    ],
  },
  {
    format: "voidshell.map",
    version: 1,
    name: "The Sunder Reach",
    note: "a warm archipelago, mostly water and bad decisions",
    params: {
      seed: 7731,
      size: 160,
      extentKm: 300,
      reliefM: 1600,
      seaLevel: 0.78,
      ridges: 0.28,
      continentality: 0.55,
      warp: 0.85,
      erosion: 10,
      latitude: 0.14,
      aridity: 0.42,
    },
    markers: [
      { id: "m0", name: "Brayhorn", u: 0.5031, v: 0.4717, kind: "peak" },
      { id: "m1", name: "Talvik", u: 0.6667, v: 0.4969, kind: "hold" },
      { id: "m2", name: "Semere", u: 0.5472, v: 0.7107, kind: "port" },
      { id: "m3", name: "Rundhollow", u: 0.7736, v: 0.4088, kind: "town" },
      { id: "m4", name: "Oshaven", u: 0.3459, v: 0.5597, kind: "hold" },
      { id: "m5", name: "Ferrest", u: 0.2138, v: 0.5535, kind: "ruin" },
    ],
  },
];
