/**
 * The maps that are already there on a fresh install.
 *
 * Two of the three are original terrain — thirteen parameters and a seed,
 * generated by the same forge the user gets. Nothing in them is traced from
 * anyone else's world.
 *
 * New York is the exception and is a different kind of thing: a hand-authored
 * reconstruction from real coordinates, described in nyc.ts. It is accurate
 * about the coastline and the skyline and invented everywhere else, which is
 * worth knowing before treating it as data. If you want a real place properly,
 * the import button reads a greyscale heightmap and that is the honest way.
 *
 * The marker coordinates are baked rather than sited at runtime. Running the
 * generator twice would give the same answer, but it would also mean paying
 * for two full terrain builds during boot to place eighteen dots — and boot is
 * exactly where that cost is least welcome.
 *
 * Which means they are only valid for the generator that placed them. Adding
 * hydrology moved every coastline on both procedural maps — erosion lowers the
 * ground and the channels cut into it — and three holds ended up in the water.
 * The check in tools/cartograph-checks.mts is what caught that, and is the
 * reason to run it after touching anything upstream of terrain.
 */
import { NYC_DOC } from "./nyc";
import type { MapDoc } from "./types";

export const EXAMPLE_DOCS: MapDoc[] = [
  // New York first. It is the one that shows what the renderer can do, and
  // the one whose ground came from somewhere real.
  NYC_DOC,
  {
    format: "voidshell.map",
    version: 1,
    name: "Kaldmark",
    note: "a northern province of holds, fells and frozen coast",
    params: {
      seed: 20489,
      size: 192,
      extentKm: 260,
      reliefM: 4200,
      seaLevel: 0.4,
      ridges: 0.72,
      continentality: 0.62,
      warp: 0.52,
      erosion: 18,
      rainfall: 0.72,
      riverDensity: 0.62,
      latitude: 0.82,
      aridity: 0.24,
    },
    markers: [
      { id: "m0", name: "Kraetind", u: 0.5183, v: 0.534, kind: "peak" },
      { id: "m1", name: "Feistad", u: 0.5812, v: 0.3037, kind: "hold" },
      { id: "m2", name: "Ruhaven", u: 0.3927, v: 0.1257, kind: "port" },
      { id: "m3", name: "Nythorpe", u: 0.6021, v: 0.4398, kind: "town" },
      { id: "m4", name: "Grehold", u: 0.1832, v: 0.6911, kind: "hold" },
      { id: "m5", name: "Snauhollow", u: 0.3927, v: 0.5236, kind: "ruin" },
      { id: "m6", name: "Hythorpe", u: 0.1518, v: 0.2775, kind: "town" },
      { id: "m7", name: "Kyhearth", u: 0.3037, v: 0.6335, kind: "camp" },
      { id: "m8", name: "Sohaven", u: 0.8691, v: 0.5602, kind: "port" },
    ],
  },
  {
    format: "voidshell.map",
    version: 1,
    name: "The Sunder Reach",
    note: "a warm archipelago, mostly water and bad decisions",
    params: {
      seed: 7731,
      size: 160,
      extentKm: 300,
      reliefM: 1600,
      seaLevel: 0.78,
      ridges: 0.28,
      continentality: 0.55,
      warp: 0.85,
      erosion: 10,
      rainfall: 0.5,
      riverDensity: 0.3,
      latitude: 0.14,
      aridity: 0.42,
    },
    markers: [
      { id: "m0", name: "Stahorn", u: 0.5031, v: 0.4717, kind: "peak" },
      { id: "m1", name: "Gaedholm", u: 0.3145, v: 0.5786, kind: "hold" },
      { id: "m2", name: "Thumstrand", u: 0.4403, v: 0.7107, kind: "port" },
      { id: "m3", name: "Skauford", u: 0.6415, v: 0.478, kind: "town" },
      { id: "m4", name: "Fraurdholm", u: 0.6541, v: 0.3145, kind: "hold" },
      { id: "m5", name: "Seirwick", u: 0.1761, v: 0.5723, kind: "ruin" },
    ],
  },
];
