/**
 * The card pool.
 *
 * Data, not behaviour: every card is a name, a phase it becomes available in, a
 * draw weight, and a list of effects that `effects.ts` knows how to apply.
 * Adding a card means adding a record here and nothing else, which is the whole
 * reason the effect engine is written the way it is.
 *
 * `phase` gates availability, `weight` biases the draw, and `rarity` is
 * presentation only.
 */

import type { Card } from "./types";

export const CARDS: Card[] = [
  {
    id: "pocket_change",
    name: "Pocket Change",
    desc: "You rummage through the battlefield and find some loose coins.",
    rarity: "common",
    phase: 1,
    weight: 3,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 10 }],
  },
  {
    id: "war_tax",
    name: "War Tax",
    desc: "The king levies a tax on both sides to fund the ongoing absurdity.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    tags: ["economy"],
    effects: [{ type: "gold", player: "both", amount: 5 }],
  },
  {
    id: "pawn_stimulus",
    name: "Pawn Stimulus Package",
    desc: "The treasury sends a bailout check to every pawn on your side.",
    rarity: "common",
    phase: 1,
    weight: 2.8,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 15 }],
  },
  {
    id: "street_hustle",
    name: "Street Hustle",
    desc: "Your bishop runs a three-card monte scheme between moves.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 8 }],
  },
  {
    id: "lucky_penny",
    name: "Lucky Penny",
    desc: "A pawn trips over a coin and gains unearned confidence.",
    rarity: "common",
    phase: 1,
    weight: 3,
    tags: ["economy", "buff"],
    effects: [{ type: "gold", player: "self", amount: 5 }, { type: "chaos", player: "self", amount: 3 }],
  },
  {
    id: "minor_ward",
    name: "Minor Ward",
    desc: "A faint magical shimmer protects one of your pieces from harm.",
    rarity: "uncommon",
    phase: 1,
    weight: 2,
    tags: ["buff", "defense"],
    effects: [{ type: "shield", target: "random_self", duration: 2 }],
  },
  {
    id: "pawn_pep_talk",
    name: "Pawn Pep Talk",
    desc: "Your king gives an inspiring speech and the pawns feel slightly less expendable.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    tags: ["buff"],
    effects: [{ type: "chaos", player: "self", amount: 5 }],
  },
  {
    id: "toll_bridge",
    name: "Toll Bridge",
    desc: "You erect a toll booth on a diagonal — the enemy bishop is furious.",
    rarity: "uncommon",
    phase: 1,
    weight: 2,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 12 }],
  },
  {
    id: "foragers_luck",
    name: "Forager's Luck",
    desc: "Your knights discover a mushroom patch in no-man's-land.",
    rarity: "common",
    phase: 1,
    weight: 2.8,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 7 }],
  },
  {
    id: "chaotic_vibes",
    name: "Chaotic Vibes",
    desc: "Everyone on the board feels a strange tingle — chaos energy surges.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    tags: ["chaos"],
    effects: [{ type: "chaos", player: "both", amount: 5 }],
  },
  {
    id: "cold_shoulder",
    name: "Cold Shoulder",
    desc: "You give a random enemy piece the cold shoulder. Literally.",
    rarity: "uncommon",
    phase: 1,
    weight: 2,
    tags: ["debuff"],
    effects: [{ type: "freeze", target: "random_enemy", duration: 1 }],
  },
  {
    id: "minor_tremor_card",
    name: "Minor Tremor",
    desc: "A small quake displaces a random piece.",
    rarity: "uncommon",
    phase: 1,
    weight: 2,
    tags: ["movement"],
    effects: [{ type: "teleport", target: "random_any" }],
  },
  {
    id: "pawn_shop",
    name: "Pawn Shop",
    desc: "You sell the concept of a pawn and receive gold in return.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 9 }],
  },
  {
    id: "battlefield_salvage",
    name: "Battlefield Salvage",
    desc: "Your squires scour the field and bring back some valuables.",
    rarity: "common",
    phase: 1,
    weight: 3,
    tags: ["economy"],
    effects: [{ type: "gold", player: "both", amount: 3 }],
  },
  {
    id: "diplomatic_immunity",
    name: "Diplomatic Immunity",
    desc: "One of your pieces gets a temporary get-out-of-jail-free card.",
    rarity: "uncommon",
    phase: 1,
    weight: 2,
    tags: ["defense"],
    effects: [{ type: "shield", target: "random_self", duration: 3 }],
  },
  {
    id: "sniper_shot",
    name: "Sniper Shot",
    desc: "A crossbow bolt eliminates a random enemy piece from across the board.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.8,
    tags: ["damage"],
    effects: [{ type: "destroy", target: "random_enemy" }],
  },
  {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    desc: "A bolt from the heavens strikes a random piece.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.8,
    tags: ["damage", "environmental"],
    effects: [{ type: "destroy", target: "random_any" }],
  },
  {
    id: "gold_rush",
    name: "Gold Rush",
    desc: "A vein of gold is discovered under the board. Everyone gets rich.",
    rarity: "uncommon",
    phase: 2,
    weight: 2,
    tags: ["economy"],
    effects: [{ type: "gold", player: "both", amount: 8 }],
  },
  {
    id: "chaos_spike",
    name: "Chaos Spike",
    desc: "The chaos meter explodes momentarily, flooding both sides with energy.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    tags: ["chaos"],
    effects: [{ type: "chaos", player: "both", amount: 8 }],
  },
  {
    id: "random_teleport",
    name: "Wild Teleport",
    desc: "A random piece blinks to a new location.",
    rarity: "common",
    phase: 2,
    weight: 2,
    tags: ["movement"],
    effects: [{ type: "teleport", target: "random_any" }],
  },
  {
    id: "clone_soldier",
    name: "Clone Soldier",
    desc: "The alchemists replicate one of your pawns.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    tags: ["chaos"],
    effects: [{ type: "clone", target: "random_self" }],
  },
  {
    id: "freeze_ray",
    name: "Freeze Ray",
    desc: "An ice cannon locks an enemy piece in place.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.8,
    tags: ["debuff"],
    effects: [{ type: "freeze", target: "random_enemy", duration: 2 }],
  },
  {
    id: "tax_the_rich",
    name: "Tax the Rich",
    desc: "You steal from the opponent's coffers in the name of justice.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    tags: ["economy"],
    effects: [{ type: "steal_gold", amount: 5 }],
  },
  {
    id: "pawn_promotion_early",
    name: "Field Promotion",
    desc: "A pawn is spontaneously promoted to knight.",
    rarity: "rare",
    phase: 2,
    weight: 1.2,
    tags: ["transform"],
    effects: [{ type: "transform", target: "random_self", into: "n" }],
  },
  {
    id: "mass_chaos",
    name: "Mass Chaos",
    desc: "The battlefield descends into total confusion for one glorious turn.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    tags: ["chaos"],
    effects: [{ type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }],
  },
  {
    id: "nuclear_pawn",
    name: "Nuclear Pawn",
    desc: "A pawn detonates, destroying everything in a 2-square radius.",
    rarity: "rare",
    phase: 3,
    weight: 1,
    tags: ["damage", "destruction"],
    effects: [{ type: "destroy", target: "random_any", radius: 2 }],
  },
  {
    id: "queen_swap",
    name: "Royal Exchange",
    desc: "Two random pieces swap positions mid-game.",
    rarity: "rare",
    phase: 3,
    weight: 1.2,
    tags: ["movement", "chaos"],
    effects: [{ type: "swap", target: "random_any" }],
  },
  {
    id: "mass_freeze",
    name: "Arctic Blast",
    desc: "Three random pieces are encased in ice.",
    rarity: "rare",
    phase: 3,
    weight: 0.9,
    tags: ["debuff"],
    effects: [{ type: "freeze", target: "random_any", duration: 2 }, { type: "freeze", target: "random_any", duration: 2 }, { type: "freeze", target: "random_enemy", duration: 3 }],
  },
  {
    id: "gold_bomb",
    name: "Gold Bomb",
    desc: "An explosion of gold coins rains down on you.",
    rarity: "rare",
    phase: 3,
    weight: 1,
    tags: ["economy"],
    effects: [{ type: "gold", player: "self", amount: 20 }],
  },
  {
    id: "army_of_pawns",
    name: "Army of Pawns",
    desc: "Three new pawns join your side from the reserves.",
    rarity: "rare",
    phase: 3,
    weight: 0.8,
    tags: ["chaos"],
    effects: [{ type: "spawn", piece: "p", square: "random_empty" }, { type: "spawn", piece: "p", square: "random_empty" }, { type: "spawn", piece: "p", square: "random_empty" }],
  },
  {
    id: "ascension_card",
    name: "Ascension",
    desc: "A random piece ascends to become a queen.",
    rarity: "epic",
    phase: 3,
    weight: 0.7,
    tags: ["transform"],
    effects: [{ type: "transform", target: "random_any", into: "q" }],
  },
  {
    id: "apocalypse",
    name: "Apocalypse",
    desc: "All pawns on both sides are obliterated.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    tags: ["damage", "destruction"],
    effects: [{ type: "destroy", target: "all_pawns" }],
  },
  {
    id: "board_wipe",
    name: "Board Wipe",
    desc: "A cataclysm destroys multiple pieces on both sides.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    tags: ["damage"],
    effects: [{ type: "destroy", target: "random_any", radius: 2 }, { type: "destroy", target: "random_any", radius: 2 }],
  },
  {
    id: "dimensional_shift",
    name: "Dimensional Shift",
    desc: "Multiple pieces teleport simultaneously.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    tags: ["teleport", "chaos"],
    effects: [{ type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }],
  },
  {
    id: "ragnarok_card",
    name: "Ragnarök",
    desc: "The end of all things. Everything burns.",
    rarity: "legendary",
    phase: 5,
    weight: 0.3,
    tags: ["destruction", "chaos"],
    effects: [{ type: "destroy", target: "random_any", radius: 3 }, { type: "chaos", player: "both", amount: 10 }],
  },
  {
    id: "gods_hand",
    name: "God's Hand",
    desc: "The divine hand rearranges the board entirely.",
    rarity: "legendary",
    phase: 5,
    weight: 0.3,
    tags: ["chaos", "teleport"],
    effects: [{ type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }],
  },
];
