/**
 * The chaos event pool — what the board does to you, as opposed to what you
 * play at it. Same shape as a card, plus a `cooldown` in turns so the same
 * event cannot fire twice in a row.
 */

import type { ChaosEvent } from "./types";

export const EVENTS: ChaosEvent[] = [
  {
    id: "minor_tremor",
    name: "Minor Tremor",
    desc: "A small earthquake displaces a random piece.",
    rarity: "common",
    phase: 1,
    weight: 3,
    cooldown: 2,
    effects: [{ type: "teleport", target: "random_any" }],
  },
  {
    id: "gold_dust_wind",
    name: "Gold Dust Wind",
    desc: "A shimmering breeze scatters gold coins across the battlefield.",
    rarity: "common",
    phase: 1,
    weight: 3.5,
    cooldown: 2,
    effects: [{ type: "gold", player: "both", amount: 3 }],
  },
  {
    id: "fog_wisp",
    name: "Fog Wisp",
    desc: "A thin mist rolls in, briefly obscuring part of the board.",
    rarity: "common",
    phase: 1,
    weight: 3,
    cooldown: 3,
    effects: [{ type: "place_hazard", hazard_id: "fog", duration: 2 }],
  },
  {
    id: "wandering_pawn",
    name: "Wandering Pawn",
    desc: "A confused pawn stumbles off course.",
    rarity: "common",
    phase: 1,
    weight: 2.5,
    cooldown: 2,
    effects: [{ type: "teleport", target: "all_pawns" }],
  },
  {
    id: "lucky_find",
    name: "Lucky Find",
    desc: "A soldier trips over buried treasure.",
    rarity: "common",
    phase: 2,
    weight: 2.5,
    cooldown: 2,
    effects: [{ type: "gold", player: "both", amount: 5 }],
  },
  {
    id: "sudden_frost",
    name: "Sudden Frost",
    desc: "An unexpected chill freezes a random piece in place.",
    rarity: "common",
    phase: 2,
    weight: 2,
    cooldown: 3,
    effects: [{ type: "freeze", target: "random_any", duration: 1 }],
  },
  {
    id: "minor_explosion",
    name: "Minor Explosion",
    desc: "A powder keg ignites, scattering a piece.",
    rarity: "common",
    phase: 2,
    weight: 2,
    cooldown: 3,
    effects: [{ type: "teleport", target: "random_any" }, { type: "chaos", player: "both", amount: 2 }],
  },
  {
    id: "lightning_strike",
    name: "Lightning Strike",
    desc: "Lightning obliterates a random piece in a shower of sparks.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.8,
    cooldown: 4,
    effects: [{ type: "destroy", target: "random_any" }],
  },
  {
    id: "meteor_shower",
    name: "Meteor Shower",
    desc: "Small meteors rain down, destroying a piece and scattering others.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    cooldown: 4,
    effects: [{ type: "destroy", target: "random_any" }, { type: "teleport", target: "random_any" }],
  },
  {
    id: "chaos_surge",
    name: "Chaos Surge",
    desc: "A wave of chaotic energy floods the board.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.5,
    cooldown: 3,
    effects: [{ type: "chaos", player: "both", amount: 5 }],
  },
  {
    id: "piece_swap",
    name: "Mysterious Swap",
    desc: "Two random pieces switch positions in the confusion.",
    rarity: "uncommon",
    phase: 2,
    weight: 1.8,
    cooldown: 4,
    effects: [{ type: "swap", target: "random_any" }],
  },
  {
    id: "gold_heist",
    name: "Gold Heist",
    desc: "A thief raids the treasury — gold flows to a random player.",
    rarity: "uncommon",
    phase: 3,
    weight: 1.5,
    cooldown: 4,
    effects: [{ type: "gold", player: "self", amount: 8 }],
  },
  {
    id: "clone_event",
    name: "The Clone Wars",
    desc: "A random piece is duplicated onto an empty square.",
    rarity: "rare",
    phase: 3,
    weight: 1.2,
    cooldown: 5,
    effects: [{ type: "clone", target: "random_any" }],
  },
  {
    id: "volcanic_eruption",
    name: "Volcanic Eruption",
    desc: "A volcano erupts, destroying a piece and leaving fire behind.",
    rarity: "rare",
    phase: 3,
    weight: 1,
    cooldown: 5,
    effects: [{ type: "destroy", target: "random_any", radius: 1 }, { type: "place_hazard", hazard_id: "fire", duration: 3 }],
  },
  {
    id: "mass_teleport",
    name: "Dimensional Rift",
    desc: "Multiple pieces are flung to random locations.",
    rarity: "rare",
    phase: 3,
    weight: 1,
    cooldown: 5,
    effects: [{ type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }],
  },
  {
    id: "twin_lightning",
    name: "Twin Lightning",
    desc: "Two bolts strike the board simultaneously.",
    rarity: "rare",
    phase: 3,
    weight: 0.8,
    cooldown: 5,
    effects: [{ type: "destroy", target: "random_any" }, { type: "destroy", target: "random_any" }],
  },
  {
    id: "chaos_vortex",
    name: "Chaos Vortex",
    desc: "A swirling vortex of chaos energy consumes a piece.",
    rarity: "rare",
    phase: 3,
    weight: 0.8,
    cooldown: 6,
    effects: [{ type: "destroy", target: "random_any", radius: 1 }, { type: "chaos", player: "both", amount: 6 }],
  },
  {
    id: "ascension_event",
    name: "Ascension",
    desc: "A random piece ascends to become a queen.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    cooldown: 8,
    effects: [{ type: "transform", target: "random_any", into: "q" }],
  },
  {
    id: "black_hole",
    name: "Black Hole Rift",
    desc: "A black hole tears open, destroying and teleporting nearby pieces.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    cooldown: 8,
    effects: [{ type: "destroy", target: "random_any", radius: 2 }, { type: "teleport", target: "random_any" }],
  },
  {
    id: "gold_apocalypse",
    name: "Gold Apocalypse",
    desc: "The economy collapses and rebuilds.",
    rarity: "epic",
    phase: 4,
    weight: 0.5,
    cooldown: 8,
    effects: [{ type: "gold", player: "both", amount: -5 }, { type: "gold", player: "both", amount: 12 }],
  },
  {
    id: "armageddon",
    name: "Armageddon",
    desc: "The ultimate cataclysm strikes — all pawns are destroyed.",
    rarity: "legendary",
    phase: 5,
    weight: 0.3,
    cooldown: 10,
    effects: [{ type: "destroy", target: "all_pawns" }],
  },
  {
    id: "dimensional_collapse",
    name: "Dimensional Collapse",
    desc: "Reality collapses — multiple pieces are flung across the board.",
    rarity: "legendary",
    phase: 5,
    weight: 0.3,
    cooldown: 10,
    effects: [{ type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }, { type: "teleport", target: "random_any" }, { type: "chaos", player: "both", amount: 8 }],
  },
  {
    id: "supernova",
    name: "Supernova",
    desc: "A dying star explodes, bathing the board in cosmic energy.",
    rarity: "legendary",
    phase: 5,
    weight: 0.3,
    cooldown: 10,
    effects: [{ type: "destroy", target: "random_any", radius: 3 }, { type: "chaos", player: "both", amount: 10 }],
  },
  {
    id: "ragnarok",
    name: "Ragnarök",
    desc: "The twilight of the gods descends, reshaping the entire board.",
    rarity: "legendary",
    phase: 5,
    weight: 0.2,
    cooldown: 12,
    effects: [{ type: "destroy", target: "random_any", radius: 3 }, { type: "destroy", target: "random_enemy", radius: 2 }, { type: "place_hazard", hazard_id: "fire", duration: 5 }, { type: "chaos", player: "both", amount: 10 }],
  },
];
