/**
 * Pawnageddon — chess, plus the deck that ruins it.
 *
 * Ported from `MrFr3nchy/pawnageddon`, whose JavaScript tree holds the rules
 * and whose React tree does not survive the trip: voidshell modules render DOM
 * and canvas through the kernel, so the presentation is rebuilt here against
 * the module SDK and only the game logic is carried over.
 *
 * **Art provenance:** the piece sprites were AI-generated by the repo owner for
 * Pawnageddon. No third-party artwork is involved. `sprites.ts` documents how
 * 29MB of source PNGs become the 16KB sheet that ships.
 *
 * **Why this is compiled in rather than seeded as a stock module.** A stock
 * module is single-file, import-free source planted into `~/modules` on first
 * run and carried inside `stock.generated.ts` for every user on every boot.
 * Pawnageddon is ~50KB of game logic across a dozen files plus a binary sheet;
 * putting that through the stock pipeline would inflate a file every session
 * pays for, to ship a game most sessions never open. So it is registered
 * directly in `main.ts`, the way `arcade` and `cartograph` are, and it is
 * deliberately absent from `STOCK_IDS` and `PORTABLE`.
 */

import type { KernelContext, VoidModule } from "../../kernel/types";
import { getPiece, isWhitePiece } from "./board";
import { DECK_TURN, EXTRA_DRAW_COST, SHOP_TURN, squareName } from "./constants";
import { PawnGame } from "./game";
import { SHIELD_LIST, WEAPON_LIST } from "./equipment";
import { getUltimate } from "./ultimates";
import { mountBoard } from "./view";
import { titleUrl } from "./sprites";
import type { Card } from "./types";

const el = <K extends keyof HTMLElementTagNameMap>(
  tag: K,
  className?: string,
  text?: string
): HTMLElementTagNameMap[K] => {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
};

const PROMOTIONS: { kind: "q" | "r" | "b" | "n"; label: string }[] = [
  { kind: "q", label: "Queen" },
  { kind: "r", label: "Rook" },
  { kind: "b", label: "Bishop" },
  { kind: "n", label: "Knight" },
];

/**
 * `surfaceId` is a getter, not a string: `render` runs *before* `openSurface`
 * returns, so the id does not exist yet at this point. Everything that needs
 * it reads it later, from an event handler.
 */
function renderGame(root: HTMLElement, ctx: KernelContext, surfaceId: () => string): () => void {
  const game = new PawnGame();

  root.className = "pg";

  const boardHost = el("div", "pg-board");
  const side = el("aside", "pg-side");
  root.append(boardHost, side);

  // ── Side panel scaffolding ──

  const banner = el("img", "pg-banner");
  banner.src = titleUrl();
  banner.alt = "Pawnageddon";
  // Decorative: the panel title already names the app, so a screen reader
  // reading the logo as well would just be saying it twice.
  banner.setAttribute("aria-hidden", "true");
  banner.decoding = "async";

  const status = el("div", "pg-status");
  const turnLine = el("div", "pg-turn");
  const phaseLine = el("div", "pg-phase");
  status.append(turnLine, phaseLine);

  const meters = el("div", "pg-meters");
  const goldLine = el("div", "pg-meter");
  const chaosLine = el("div", "pg-meter");
  const chaosBar = el("div", "pg-bar");
  const chaosFill = el("div", "pg-bar-fill");
  chaosBar.append(chaosFill);
  meters.append(goldLine, chaosLine, chaosBar);

  const actions = el("div", "pg-actions");
  const ultButton = el("button", "pg-btn");
  ultButton.type = "button";
  const drawButton = el("button", "pg-btn");
  drawButton.type = "button";
  drawButton.textContent = "Draw card";
  const newButton = el("button", "pg-btn pg-btn-quiet");
  newButton.type = "button";
  newButton.textContent = "New game";
  actions.append(ultButton, drawButton, newButton);

  const shop = el("div", "pg-shop");
  const shopTitle = el("h3", "pg-h", "Equip");
  const shopRow = el("div", "pg-shop-row");
  shop.append(shopTitle, shopRow);

  const handWrap = el("div", "pg-hand");
  const handTitle = el("h3", "pg-h", "Hand");
  const handRow = el("div", "pg-hand-row");
  handWrap.append(handTitle, handRow);

  const capturedWrap = el("div", "pg-captured");

  const logWrap = el("div", "pg-log");

  side.append(banner, status, meters, actions, shop, handWrap, capturedWrap, logWrap);

  // The promotion chooser is a sheet over the board. It needs the `hidden`
  // guard: this stylesheet sets `display` on it, and an author rule outranks
  // the UA stylesheet, so without it `hidden = true` would do nothing and
  // leave an invisible sheet swallowing every click on the board.
  const promo = el("div", "pg-promo");
  promo.hidden = true;
  const promoTitle = el("div", "pg-promo-title", "Promote to");
  const promoRow = el("div", "pg-promo-row");
  promo.append(promoTitle, promoRow);
  boardHost.append(promo);

  // ── Sound ──

  const sound = {
    move: () => ctx.audio.burst({ freq: 240, q: 2, gain: 0.18, decay: 0.08 }),
    capture: () => ctx.audio.burst({ freq: 120, q: 1.2, gain: 0.3, decay: 0.18 }),
    check: () => ctx.audio.tone({ freq: 660, toFreq: 880, gain: 0.16, decay: 0.22 }),
    boom: () => ctx.audio.burst({ freq: 70, q: 0.8, gain: 0.4, decay: 0.5 }),
  };

  // ── Painting ──

  const paint = (): void => {
    const mover = game.whiteToMove ? "White" : "Black";
    if (game.gameOver) {
      turnLine.textContent =
        game.gameOver === "checkmate"
          ? `Checkmate — ${game.winner === "white" ? "White" : "Black"} wins`
          : "Stalemate — a draw";
    } else {
      turnLine.textContent = `${mover} to move${game.inCheck ? " — check" : ""}`;
    }
    turnLine.classList.toggle("bad", Boolean(game.gameOver) || game.inCheck);

    phaseLine.textContent = `Phase ${game.phase} · ${game.phaseName} · turn ${game.turnCount}`;

    goldLine.textContent = `Gold ${game.currentGold}`;
    chaosLine.textContent = `Chaos ${Math.round(game.currentChaos)}`;
    chaosFill.style.width = `${Math.max(0, Math.min(100, game.currentChaos))}%`;

    paintUltimate();
    paintShop();
    paintHand();
    paintCaptured();
    paintLog();

    drawButton.disabled = Boolean(game.gameOver) || !game.deckUnlocked;
    drawButton.title = game.deckUnlocked
      ? `Draw a card (${EXTRA_DRAW_COST} gold)`
      : `The deck opens on turn ${DECK_TURN}`;

    const id = surfaceId();
    if (id) {
      ctx.setTitle(
        id,
        game.gameOver
          ? `Pawnageddon — ${game.gameOver}`
          : `Pawnageddon — ${mover.toLowerCase()} to move`
      );
    }
  };

  function paintUltimate(): void {
    const sel = game.selected;
    const piece = sel ? getPiece(game.board, sel[0], sel[1]) : " ";
    const ult = sel ? getUltimate(piece) : null;
    if (!sel || !ult) {
      ultButton.textContent = "Ultimate";
      ultButton.disabled = true;
      ultButton.title = "Select one of your pieces";
      return;
    }
    const affordable = game.currentChaos >= ult.chaosCost;
    ultButton.textContent = `${ult.icon} ${ult.name} — ${ult.chaosCost}`;
    ultButton.disabled = !affordable || Boolean(game.gameOver);
    ultButton.title = `${ult.desc}${affordable ? "" : " (not enough chaos)"}`;
  }

  function paintShop(): void {
    shopRow.replaceChildren();
    const sel = game.selected;
    const owned = sel && isWhitePiece(getPiece(game.board, sel[0], sel[1])) === game.whiteToMove;
    if (!game.shopUnlocked) {
      shop.classList.add("pg-muted");
      shopTitle.textContent = `Equip — opens on turn ${SHOP_TURN}`;
      return;
    }
    shop.classList.remove("pg-muted");
    shopTitle.textContent = owned
      ? `Equip ${squareName(sel![0], sel![1])}`
      : "Equip — select one of your pieces";
    if (!owned) return;

    const stock: [typeof WEAPON_LIST, "weapon" | "shield"][] = [
      [WEAPON_LIST, "weapon"],
      [SHIELD_LIST, "shield"],
    ];
    for (const [list, kind] of stock) {
      for (const item of list) {
        const btn = el("button", "pg-chip");
        btn.type = "button";
        btn.textContent = `${item.icon} ${item.name} ${item.cost}`;
        btn.title = item.desc;
        btn.disabled = game.currentGold < item.cost || Boolean(game.gameOver);
        btn.addEventListener("click", () => game.equip(sel![0], sel![1], item.id, kind));
        shopRow.append(btn);
      }
    }
  }

  function paintHand(): void {
    handRow.replaceChildren();
    const hand = game.currentHand;
    handTitle.textContent = game.deckUnlocked ? `Hand (${hand.length})` : "Hand — opens on turn 8";
    if (!hand.length) {
      handRow.append(el("p", "pg-empty", game.deckUnlocked ? "No cards." : "Locked."));
      return;
    }
    for (const card of hand) {
      handRow.append(cardButton(card));
    }
  }

  function cardButton(card: Card): HTMLElement {
    const btn = el("button", `pg-card pg-${card.rarity}`);
    btn.type = "button";
    btn.append(el("strong", undefined, card.name));
    btn.append(el("span", "pg-card-desc", card.desc));
    btn.disabled = Boolean(game.gameOver) || game.cardsPlayedThisTurn >= 1;
    btn.title = game.cardsPlayedThisTurn >= 1 ? "One card per turn" : "Play this card";
    btn.addEventListener("click", () => game.playCard(card.id));
    return btn;
  }

  function paintCaptured(): void {
    capturedWrap.replaceChildren();
    const line = (label: string, pieces: string[]) => {
      const row = el("div", "pg-captured-row");
      row.append(el("span", "pg-captured-label", label));
      row.append(el("span", "pg-captured-list", pieces.join(" ") || "—"));
      return row;
    };
    // `capturedWhite` holds white pieces that were lost, so it is black's haul.
    capturedWrap.append(line("Black took", game.capturedWhite));
    capturedWrap.append(line("White took", game.capturedBlack));
  }

  function paintLog(): void {
    logWrap.replaceChildren();
    const messages = game.turnMessages.slice(-8);
    if (!messages.length) {
      logWrap.append(el("p", "pg-empty", "Quiet, for now."));
      return;
    }
    for (const m of messages) logWrap.append(el("p", "pg-log-line", m));
  }

  // ── Promotion ──

  const showPromotion = (white: boolean): void => {
    promoRow.replaceChildren();
    for (const { kind, label } of PROMOTIONS) {
      const btn = el("button", "pg-btn");
      btn.type = "button";
      btn.textContent = label;
      btn.addEventListener("click", () => {
        promo.hidden = true;
        game.choosePromotion(kind);
      });
      promoRow.append(btn);
    }
    promoTitle.textContent = `Promote — ${white ? "White" : "Black"}`;
    promo.hidden = false;
  };

  // ── Wiring ──

  const board = mountBoard(boardHost, ctx, game, (col, row) => game.clickSquare(col, row));

  const offs = [
    game.on("change", paint),
    game.on("promotionNeeded", ({ white }) => showPromotion(white)),
    game.on("moved", ({ captured }) => {
      if (!ctx.audio.enabled()) return;
      if (captured !== " ") sound.capture();
      else sound.move();
    }),
    game.on("check", () => {
      if (ctx.audio.enabled()) sound.check();
    }),
    game.on("ultimate", ({ name }) => {
      if (ctx.audio.enabled()) sound.boom();
      ctx.notify(`${name} tears through the board`, "info");
    }),
    game.on("blocked", ({ col, row }) => {
      ctx.notify(`The piece on ${squareName(col, row)} held`, "info");
    }),
    game.on("phaseUp", ({ phase, name }) => {
      ctx.notify(`Phase ${phase} — ${name}`, "warn");
    }),
    game.on("chaosEvent", ({ name, desc }) => {
      ctx.notify(`${name}: ${desc}`, "info");
    }),
    game.on("gameOver", ({ result, winner }) => {
      ctx.notify(
        result === "checkmate" ? `Checkmate — ${winner} wins` : "Stalemate",
        result === "checkmate" ? "good" : "info"
      );
      ctx.log(`game over: ${result}${winner ? ` (${winner})` : ""}`);
    }),
  ];

  ultButton.addEventListener("click", () => {
    const sel = game.selected;
    if (sel) game.useUltimate(sel[0], sel[1]);
  });
  drawButton.addEventListener("click", () => game.drawCard());
  newButton.addEventListener("click", () => {
    // Reopening the surface is the honest way to restart: the game owns a deck,
    // a chaos engine and a board, and half-resetting one of those is how a "new
    // game" ends up still carrying the old one's hazards.
    const id = surfaceId();
    if (id) ctx.closeSurface(id);
    ctx.launch("pawnageddon");
  });

  game.start();
  paint();

  return () => {
    for (const off of offs) off();
    board.dispose();
  };
}

export const pawnageddon: VoidModule = {
  manifest: {
    id: "pawnageddon",
    name: "Pawnageddon",
    kind: "app",
    glyph: "♟",
    blurb: "chess, plus the deck that ruins it",
    version: "0.1.0",
  },

  activate(ctx: KernelContext) {
    ctx.defineCommand({
      id: "pawnageddon.open",
      label: "pawnageddon",
      hint: "chess with a chaos deck",
      glyph: "♟",
      run: (c) => c.launch("pawnageddon"),
    });
    return () => {
      /* the command is withdrawn by the kernel on uninstall */
    };
  },

  launch(ctx: KernelContext) {
    // Assigned as soon as openSurface returns; render() runs before that, and
    // everything that reads it does so from a handler, later.
    let sid = "";
    const surface = ctx.openSurface({
      title: "Pawnageddon",
      width: 900,
      height: 620,
      render: (root, c) => renderGame(root, c, () => sid),
    });
    sid = surface.id;
  },
};
