/**
 * The piece sprite sheet.
 *
 * **Art provenance:** every piece was AI-generated by the repo owner for
 * Pawnageddon. No third-party artwork is involved, and none of it is traced
 * from or derived from an existing chess set.
 *
 * The sources are twelve 1024x1536 PNGs totalling 29MB, which is not something
 * a bundle can carry. `tools/pawnageddon-sprites.py` trims, rescales and packs
 * them into one 16KB lossless WebP; that script is the authority on how the
 * sheet is produced and why, and it must be re-run if the source art changes.
 *
 * The layout it produces, which everything below depends on:
 *
 *   6 columns x 2 rows of 96x128 cells
 *   columns: pawn, knight, bishop, rook, queen, king
 *   rows:    0 = white, 1 = black
 *
 * Pieces are bottom-aligned inside their cell and scaled against one shared
 * tallest-piece height, so blitting a whole cell onto a board square both puts
 * the piece on the square rather than floating above it and keeps a pawn
 * visibly shorter than a king.
 */

import type { Piece, PieceKind } from "./types";

export const CELL_W = 96;
export const CELL_H = 128;

/** Column order in the sheet: pawn, knight, bishop, rook, queen, king. */
export const SHEET_ORDER: PieceKind[] = ["p", "n", "b", "r", "q", "k"];

/** Where a piece's cell sits in the sheet, in pixels. */
export function cellFor(piece: Piece): { sx: number; sy: number } | null {
  if (piece === " ") return null;
  const kind = piece.toLowerCase() as PieceKind;
  const col = SHEET_ORDER.indexOf(kind);
  if (col < 0) return null;
  // Lowercase is white, and white is row 0.
  const row = piece === piece.toLowerCase() ? 0 : 1;
  return { sx: col * CELL_W, sy: row * CELL_H };
}

export interface SpriteSheet {
  image: HTMLImageElement | null;
  ready: boolean;
}

/**
 * Start loading the sheet.
 *
 * Resolved through `import.meta.url` rather than a bare `import` of the file:
 * Vite treats both as assets and emits the same hashed URL, but only this form
 * survives being bundled by esbuild for the headless harness, which has no
 * loader for `.webp` and no need for one — jsdom never paints.
 */
export function loadSheet(onReady: () => void): SpriteSheet {
  const sheet: SpriteSheet = { image: null, ready: false };
  if (typeof Image === "undefined") return sheet;
  const img = new Image();
  img.decoding = "async";
  img.addEventListener("load", () => {
    sheet.ready = true;
    onReady();
  });
  // A sheet that fails to load must not take the game down: the board falls
  // back to drawing letters, which is ugly but playable.
  img.addEventListener("error", () => {
    sheet.ready = false;
  });
  img.src = new URL("./pieces.webp", import.meta.url).href;
  sheet.image = img;
  return sheet;
}

export function titleUrl(): string {
  return new URL("./title.jpg", import.meta.url).href;
}
