/**
 * Regenerates packages/api/src/wordlist.ts.
 *
 * Run this only when the list needs to change — the output is checked in, so
 * the API has no build step and no network dependency. Changing the list
 * invalidates nothing: existing keys are stored as hashes and are still
 * accepted, they just can no longer be regenerated from this list.
 *
 *   curl -sO https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
 *   npx esbuild tools/build-wordlist.mts --bundle --platform=node \
 *     --format=esm --outfile=bw.mjs --log-level=error && node bw.mjs
 *
 * Source is the EFF large wordlist, which is already curated for spelling and
 * against profanity. Everything below is about making the words safe to say
 * out loud and to write down from memory.
 */
import { readFile, writeFile } from "node:fs/promises";

/** Exactly 2^11, so each word is 11 bits and a four-word key is exactly 44. */
const TARGET = 2048;
const MIN_LEN = 3;
const MAX_LEN = 8;

/**
 * Levenshtein, abandoned as soon as it exceeds `maxd`. The full distance is
 * uninteresting here; only whether it clears the bar.
 */
function withinDistance(a: string, b: string, maxd: number): boolean {
  if (Math.abs(a.length - b.length) > maxd) return false;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i, ...new Array<number>(b.length).fill(0)];
    let best = i;
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min(
        prev[j]! + 1,
        cur[j - 1]! + 1,
        prev[j - 1]! + (a[i - 1] === b[j - 1] ? 0 : 1)
      );
      if (cur[j]! < best) best = cur[j]!;
    }
    if (best > maxd) return false;
    prev = cur;
  }
  return prev[b.length]! <= maxd;
}

const raw = await readFile(process.argv[2] ?? "eff_large_wordlist.txt", "utf8");

const candidates = raw
  .split("\n")
  .map((line) => line.split("\t")[1]?.trim() ?? "")
  .filter((w) => w.length >= MIN_LEN && w.length <= MAX_LEN && /^[a-z]+$/.test(w))
  // Shorter first, so the list favours words that are quick to say and type.
  .sort((a, b) => a.length - b.length || a.localeCompare(b));

/**
 * Keep a word only if it is at least 3 edits from every word already kept.
 *
 * This one rule does the work of several blocklists. Near-homophones are
 * mostly within 2 edits (there/their, weak/week, made/maid); so are visually
 * confusable pairs, and so is every singular/plural and -ing/-ed variation.
 * Curating those by hand means enumerating English, and missing some.
 *
 * The side benefit is error tolerance: no two keys in this alphabet are within
 * two typos of each other, so a mistyped key is a failed signin rather than a
 * successful signin to somebody else's dashboard.
 */
const distinct: string[] = [];
for (const w of candidates) {
  if (!distinct.some((k) => withinDistance(w, k, 2))) distinct.push(w);
}

const short = distinct.filter((w) => w.length < MAX_LEN);
const long = distinct.filter((w) => w.length === MAX_LEN);
const need = TARGET - short.length;
if (need < 0) throw new Error(`too many short words: ${short.length} > ${TARGET}`);
if (need > long.length) {
  throw new Error(`not enough distinct words: ${distinct.length} available, ${TARGET} needed`);
}

// Stride across the long words rather than taking a prefix, so the list isn't
// silently truncated partway through the alphabet.
const stride = long.length / need;
const picked = Array.from({ length: need }, (_, i) => long[Math.floor(i * stride)]!);

const words = [...short, ...picked].sort();
if (new Set(words).size !== TARGET) throw new Error("duplicate or miscounted words");

const lines: string[] = [];
for (let i = 0; i < words.length; i += 8) {
  lines.push("  " + words.slice(i, i + 8).map((w) => `"${w}",`).join(" "));
}

await writeFile(
  "packages/api/src/wordlist.ts",
  `/**
 * The key alphabet. Generated by tools/build-wordlist.mts — do not hand-edit.
 *
 * ${TARGET} words, derived from the EFF large wordlist. Every word is lowercase
 * ASCII, ${MIN_LEN}-${MAX_LEN} characters, and at least three edits from every other word
 * in the list, which is what keeps near-homophones and visually confusable
 * pairs out without maintaining a blocklist of them.
 *
 * ${TARGET} is 2^11, so each word carries exactly 11 bits and a four-word key
 * carries exactly 44. The list being public costs nothing — all of the entropy
 * is in the selection, as with BIP39.
 */
export const WORDS: readonly string[] = [
${lines.join("\n")}
];
`,
  "utf8"
);

console.log(`wrote ${words.length} words (${distinct.length} distinct available)`);
