"""Reduce pawnageddon's 29MB of source art to a sprite sheet a bundle can carry.

The twelve source PNGs are 1024x1536 and ~2.4MB each. All of them were
AI-generated by the repo owner -- no third-party art is involved.

Two things about this asset set are load-bearing:

  * Every piece carries a faint sub-threshold alpha haze across the whole
    canvas, so a raw .getbbox() returns the entire image for all twelve and
    king-white's is literally 1024x1536. Measuring the bbox off a *thresholded*
    alpha is what makes the trim mean anything.
  * Relative height has to be preserved across the set, or a pawn ends up as
    tall as a king. Everything is scaled against one shared `tallest`.

Run it from the repo root with a pawnageddon checkout beside it, or point
PAWNAGEDDON at one:

    python3 tools/pawnageddon-sprites.py
"""
import os

from PIL import Image

# Point at a pawnageddon checkout; the art is not vendored here, only its output.
SRC = os.environ.get('PAWNAGEDDON', '../pawnageddon') + '/public/assets'
OUT = os.path.join(os.path.dirname(__file__), '..', 'packages/ui/src/modules/pawnageddon')

ORDER  = ['pawn', 'knight', 'bishop', 'rook', 'queen', 'king']
COLORS = ['white', 'black']

CELL_W, CELL_H = 96, 128
MAX_H = CELL_H - 4          # headroom so the tallest piece doesn't touch the cell edge


def load(name, color):
    im = Image.open(f'{SRC}/chess-pieces/{name}-{color}.png').convert('RGBA')
    r, g, b, a = im.split()
    a = a.point(lambda v: 0 if v < 24 else v)
    im = Image.merge('RGBA', (r, g, b, a))
    bb = a.point(lambda v: 255 if v > 128 else 0).getbbox()
    return im.crop(bb)


crops = {(n, c): load(n, c) for n in ORDER for c in COLORS}
tallest = max(im.height for im in crops.values())

sheet = Image.new('RGBA', (CELL_W * len(ORDER), CELL_H * len(COLORS)), (0, 0, 0, 0))
for ri, color in enumerate(COLORS):
    for ci, name in enumerate(ORDER):
        im = crops[(name, color)]
        h = max(1, round(MAX_H * im.height / tallest))
        w = max(1, round(im.width * h / im.height))
        if w > CELL_W - 4:
            h = round(h * (CELL_W - 4) / w)
            w = CELL_W - 4
        im = im.resize((w, h), Image.LANCZOS)
        x = ci * CELL_W + (CELL_W - w) // 2
        y = ri * CELL_H + (CELL_H - h) - 2   # bottom-aligned: pieces stand on the square
        sheet.alpha_composite(im, (x, y))

# 64-colour quantize then lossless WebP: smaller than the PNG-8 and pixel-identical
# to it, and it keeps enough distinct alpha levels that edges stay clean over the
# board squares.
sheet.quantize(colors=64, method=Image.FASTOCTREE).convert('RGBA') \
     .save(f'{OUT}/pieces.webp', lossless=True, quality=100, method=6)

title = Image.open(f'{SRC}/pawnageddon-title.png').convert('RGB')
title.resize((256, 171), Image.LANCZOS) \
     .save(f'{OUT}/title.jpg', quality=68, optimize=True, progressive=True)

print(f'tallest source crop: {tallest}px')
print(f'sheet: {sheet.width}x{sheet.height}')
